version: "3"

services:
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local
